2021-07-06 14:54:24,064 ERROR: Exception on /reset_password_request [POST] [in d:\pythonprojects\flasktest\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\pythonprojects\flasktest\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\pythonprojects\flasktest\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\pythonprojects\flasktest\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\pythonprojects\flasktest\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\PythonProjects\flaskTest\app\routes.py", line 178, in reset_password_request
    send_password_reset_email(user)
  File "D:\PythonProjects\flaskTest\app\email.py", line 15, in send_password_reset_email
    token = user.get_reset_password_token()
  File "D:\PythonProjects\flaskTest\app\models.py", line 72, in get_reset_password_token
    return jwt.encode(
AttributeError: 'str' object has no attribute 'decode'
2021-07-06 15:42:12,532 INFO: Microblog startup [in D:\PythonProjects\flaskTest\app\__init__.py:54]
2021-07-06 15:42:26,087 INFO: Microblog startup [in D:\PythonProjects\flaskTest\app\__init__.py:54]
2021-07-06 15:44:53,592 INFO: Microblog startup [in D:\PythonProjects\flaskTest\app\__init__.py:57]
2021-07-06 15:47:05,901 INFO: Microblog startup [in D:\PythonProjects\flaskTest\app\__init__.py:57]
2021-07-06 15:48:21,006 INFO: Microblog startup [in D:\PythonProjects\flaskTest\app\__init__.py:57]
